hopf_cpg_node:
  ros__parameters:
    mu: 10.0
    r_desired: 1.0
    coupling_K: 1.0
    phase_desired: [0.0, 3.1416, 3.1416, 0.0]

    stance_lift_z: 0.0035
    swing_lift_z: 0.045
    body_height: 0.0
    
    body_offset_x: 0.02
    body_offset_y: 0.015
    body_offset_z: 0.0

    omega_stance: 0.3
    omega_swing: 2.5
    turn_scale: 0.25
    freq_scale: 1.5