joy_body_ik_node:
  ros__parameters:
    filter_alpha: 0.9
    joy_type: generic
    axis_linear:
      x: 1
      y: 0
      z: 2
    axis_angular:
      roll: 4
      pitch: 5
      yaw: 3
    lock: 2
    reset: 3
