joy_teleop_node:
  ros__parameters:
    filter_alpha: 0.90
    joy_type: ps4
    max_vel:
      lin_x: 0.05
      lin_y: 0.03
      ang_z: 0.25
    gait_range:
      max_height: 0.065
      min_height: 0.025
      max_period: 1.0
      min_period: 0.25
    axis_linear:
      x: 1
      y: 0
      z: 3
    axis_angular:
      roll_inc: 14
      roll_dec: 13
      pitch_inc: 11
      pitch_dec: 12
      yaw: 2
    gait_params:
      gait_height_inc: 5
      gait_height_dec: 4
      gait_period_inc: 7
      gait_period_dec: 6
    restart: 9
    rest: 2
    lock: 0
    body: 3
    walk: 1
